"""
Scout Scholarship Models.

Defines domain models related to scholarships
and financial aid opportunities.
"""

from pydantic import Field

from backend.models.common import DomainModel


# ==========================================================
# Scholarship
# ==========================================================

class Scholarship(DomainModel):
    """
    Represents a scholarship opportunity.
    """

    name: str = Field(
        description="Official scholarship name.",
    )

    provider: str = Field(
        description="Organization offering the scholarship.",
    )

    description: str | None = Field(
        default=None,
        description="Short scholarship summary.",
    )

    eligibility: str | None = Field(
        default=None,
        description="Eligibility criteria.",
    )

    benefits: str | None = Field(
        default=None,
        description="Scholarship benefits.",
    )

    application_url: str | None = Field(
        default=None,
        description="Official application URL.",
    )

    deadline: str | None = Field(
        default=None,
        description="Application deadline.",
    )


# ==========================================================
# Scholarship Recommendation
# ==========================================================

class ScholarshipRecommendation(DomainModel):
    """
    Scholarship recommendations generated by Scout.
    """

    query: str = Field(
        description="Original user query.",
    )

    scholarships: list[Scholarship] = Field(
        default_factory=list,
        description="Recommended scholarships.",
    )


__all__ = (
    "Scholarship",
    "ScholarshipRecommendation",
)